"""add_banner_url_to_users

Revision ID: 2e0964a54db9
Revises: 0b97fbf09bcf
Create Date: 2026-03-28 15:50:34.449413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0964a54db9'
down_revision: Union[str, Sequence[str], None] = '0b97fbf09bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_url')
    # ### end Alembic commands ###
