"""increase_correct_answer_length

Revision ID: 752f670a5891
Revises: aef1c2af54e6
Create Date: 2026-04-02 16:48:05.304825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752f670a5891'
down_revision: Union[str, Sequence[str], None] = 'aef1c2af54e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
