"""update_past_questions

Revision ID: 990cfcf1861d
Revises: 2e0964a54db9
Create Date: 2026-04-02 09:32:59.884086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '990cfcf1861d'
down_revision: Union[str, Sequence[str], None] = '2e0964a54db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_table('motivations')
    op.add_column('past_questions', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('past_questions', sa.Column('file_urls', sa.JSON(), nullable=True))
    op.alter_column('past_questions', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_past_questions_department'), 'past_questions', ['department'], unique=False)
    op.drop_column('past_questions', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_questions', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_past_questions_department'), table_name='past_questions')
    op.alter_column('past_questions', 'year',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('past_questions', 'file_urls')
    op.drop_column('past_questions', 'department')
    op.create_table('motivations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quote', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('motivations_pkey'))
    )
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('status_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('interaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_activities_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_activities_pkey'))
    )
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###
