"""add_quiz_to_past_questions

Revision ID: aef1c2af54e6
Revises: cfbbeb1f3c86
Create Date: 2026-04-02 14:57:53.246587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef1c2af54e6'
down_revision: Union[str, Sequence[str], None] = 'cfbbeb1f3c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_questions', sa.Column('has_quiz', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('quiz_questions', sa.Column('past_question_id', sa.UUID(), nullable=True))
    op.alter_column('quiz_questions', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_quiz_questions_past_question_id'), 'quiz_questions', ['past_question_id'], unique=False)
    op.create_foreign_key(None, 'quiz_questions', 'past_questions', ['past_question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_questions_past_question_id'), table_name='quiz_questions')
    op.alter_column('quiz_questions', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('quiz_questions', 'past_question_id')
    op.drop_column('past_questions', 'has_quiz')
    # ### end Alembic commands ###
