"""add_level_to_past_questions

Revision ID: cfbbeb1f3c86
Revises: 990cfcf1861d
Create Date: 2026-04-02 12:18:39.864657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbbeb1f3c86'
down_revision: Union[str, Sequence[str], None] = '990cfcf1861d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_questions', sa.Column('level', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_past_questions_level'), 'past_questions', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_past_questions_level'), table_name='past_questions')
    op.drop_column('past_questions', 'level')
    # ### end Alembic commands ###
